opencl: Rename "info" to "opencl_info"
This was causing a namespace clash in autotools:

    automake-1.14: warning: redefinition of 'info' ...
    /usr/share/automake-1.14/am/program.am: ... 'info$(EXEEXT)' previously defined here
    exercises/opencl/Makefile.am:18:   while processing program 'info'

Issue #4.